name: Terraform Plan

on: [push]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      run: |
        echo Installing terraform
        snap info terraform
        sudo snap install terraform 
    
    - name: Terraform init
      run: terraform init
      
    - name: Terraform validation
      run: terraform validate
    
    - name: Terraform plan
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan

